/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_love2d_android_Channels */

#ifndef _Included_org_love2d_android_Channels
#define _Included_org_love2d_android_Channels
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_love2d_android_Channels
 * Method:    nativeClear
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_love2d_android_Channels_nativeClear
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_love2d_android_Channels
 * Method:    nativeDemand
 * Signature: (Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_love2d_android_Channels_nativeDemand
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     org_love2d_android_Channels
 * Method:    nativeGetCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_love2d_android_Channels_nativeGetCount
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_love2d_android_Channels
 * Method:    nativeHasRead
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_love2d_android_Channels_nativeHasRead
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_love2d_android_Channels
 * Method:    nativePeek
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_love2d_android_Channels_nativePeek
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_love2d_android_Channels
 * Method:    nativePop
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_love2d_android_Channels_nativePop
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_love2d_android_Channels
 * Method:    nativePush
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jint JNICALL Java_org_love2d_android_Channels_nativePush
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_love2d_android_Channels
 * Method:    nativeSupply
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_love2d_android_Channels_nativeSupply
  (JNIEnv *, jclass, jstring, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
